### ISSUE TITLE
Steal from PG 10.x to PG 10.x fails on pg_stat_statements extension

### ISSUE THREAD

**Issue by alexmic** [hellofresh/klepto#117]
I'm running a Postgres database on Heroku (10.x). The database has the pg_stat_statements extension installed. The dump includes the following:

```
--
-- Name: pg_stat_statements; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA public;


--
-- Name: EXTENSION pg_stat_statements; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_stat_statements IS 'track execution statistics of all SQL statements executed';
```

The steal command fails with the following:
```
2020/04/04 20:51:10 Error while dumping: failed to execute pre dump tables: Failed to disable triggers for pg_stat_statements: pq: "pg_stat_statements" is not a table or foreign table
```

Klepto version: 0.2

**Comment by boekkooi-fresh** [comment]
Interesting this looks like an issue with `pg_dump` and [how we use it](https://github.com/hellofresh/klepto/blob/ac1b47eb6219c692ffa261362440161b6b2c746a/pkg/reader/postgres/pg_dump.go#L38).
We probably need to add one of the following:
- better schema support using `--schema` 
- A way to exclude tables using `--exclude-table`
- Include only tables we want `--table`

There maybe other options in the [pg_dump docs](https://www.postgresql.org/docs/10/app-pgdump.html).

**Comment by alexmic** [comment]
Hey @boekkooi-fresh the issue is not so much that pg_stat_statements is included in the schema definitions but that it's thought of as a table when disabling triggers?

**Comment by luizbranco** [comment]
I have experienced a similar issue as Alex. After trying the suggested pg_dump options, I found a temporary solution by modifying the postgres reader to exclude the `pg_stat_statements` from the `GetTables` function:

```go
- WHERE table_catalog=current_database() AND table_schema NOT IN ('pg_catalog', 'information_schema')`,
+ WHERE table_catalog=current_database() AND table_schema NOT IN ('pg_catalog', 'information_schema') AND table_name NOT IN ('pg_stat_statements')`,
```

Since pg_stat_statements is excluded from the list, it doesn't trigger the `ALTER TABLE %s DISABLE TRIGGER ALL`.
