### ISSUE TITLE
Is there a way to specify the PG schema to steal from?

### ISSUE THREAD

**Issue by alexmic** [hellofresh/klepto#138]
The user running klepto does not have permissions over a schema in the database which causes pg_dump to fail. It's not possible for us to give permissions to this user since it is controlled by Heroku.

**Comment by lucasmdrs** [comment]
Hey @alexmic :wave:

Thank you for your question, the user and schema information are all provided within the DSN string, you can check an example from our [docs](https://github.com/hellofresh/klepto/blob/master/docs/usage/commands.md#steal) for PG:

```shell
klepto steal \
--from="postgres://user:pass@localhost/fromDB?sslmode=disable" 
```

**Comment by alexmic** [comment]
Hello @lucasmdrs, thank you for your reply. I'm providing the database to connect to via the DSN but this [command](https://github.com/hellofresh/klepto/blob/master/pkg/reader/postgres/pg_dump.go#L35) attempts to dump table schemas for all database schemas (in my case `public` and `_heroku`) but the database user provided to the application by Heroku does not have any privileges over the `_heroku` schema since it's used for change data capture purposes. I am basically looking for a way to specify the `--schema` option for pg_dump so that it dumps only the schemas I tell it to.

**Comment by lucasmdrs** [comment]
Thanks for clarifying @alexmic ! :slightly_smiling_face: 

I see your problem now, currently Klepto does not support any extra flags to be passed to the `pg_dump` command, implementing such change would require at least some minor changes in the source code.

However Klepto is doing a lookup for the `pg_dump` command, so what you could do is create a wrapper script that calls the original `pg_dump` binary adding any flags you want. For example:

Let's assume you have the following `PATH` environment:
```shell
echo $PATH
# /usr/local/bin/:/usr/bin/
```

And you `pg_dump` binary is located in:
```shell
which pg_dump
# /usr/bin/pg_dump
```

If you create a wrapper script in `/usr/local/bin/pg_dump`:
```shell
#!/bin/bash

/usr/bin/pg_dump $@ --schema myschema
``` 

Grant permission to execute:
```shell
chmod +x /usr/local/bin/pg_dump
``` 

Now your system and Klepto will be calling `pg_dump` from your script and your flag will be included.


I know this is not the most elegant solution, but I hope that it helps to unblock you until future changes in the source code.
